#define UNICODE
#define _UNICODE
#define _WIN32_WINNT 0x0601
#include <windows.h>
#include <commdlg.h>
#include <commctrl.h>
#include <shellapi.h>
#include <string>
#include <vector>
#include <fstream>
#include <sstream>
#include <algorithm>
#include <map>
#include <cwctype>
#include <cstring>

struct Snippet{std::wstring keyword,group,text;bool enabled=true;};
static HINSTANCE gi{}; static HWND wh{},kw{},gr{},tx{},lv{},searchBox{},statusBar{},countLbl{},modeBox{},customBox{},setCustomBtn{},modeStatus{};
static std::vector<Snippet> snips; static int editIndex=-1; static bool enabled=true, internalPaste=false, hasClip=false; static std::wstring buffer,dataPath,pendingText,clipBackup,customTrigger=L"ب"; static int pendingDelete=0; static HWND pendingTarget{}; static HHOOK hook{}; static NOTIFYICONDATAW nid{}; static HFONT font{},titleFont{},boldFont{}; static HBRUSH bgBrush{},fieldBrush{};
static const UINT WM_EXPAND=WM_APP+10, WM_TRAY=WM_APP+20, TIMER_CLIP=77, TRAY_UID=1001; enum{MODE_AUTO,MODE_CTRL_SPACE,MODE_CUSTOM_TEXT}; static int modeValue=MODE_AUTO;
enum{ID_SAVE=1,ID_NEW=2,ID_DELETE=3,ID_COPY=4,ID_IMPORT=5,ID_EXPORT=6,ID_ENABLE=10,ID_DISABLE=11,ID_MODE=12,ID_SET_CUSTOM=13,ID_KEYWORD=20,ID_GROUP=21,ID_TEXT=22,ID_SEARCH=30,ID_LIST=31,ID_CUSTOM=32,ID_TRAY_SHOW=200,ID_TRAY_ENABLE=201,ID_TRAY_DISABLE=202,ID_TRAY_EXIT=203};
static COLORREF C_BG=RGB(222,244,255),C_TEXT=RGB(12,47,70);

static std::wstring U8W(const std::string&s){if(s.empty())return L"";int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),0,0);if(n<=0){n=MultiByteToWideChar(CP_ACP,0,s.data(),(int)s.size(),0,0);std::wstring w(n,0);if(n>0)MultiByteToWideChar(CP_ACP,0,s.data(),(int)s.size(),w.data(),n);return w;}std::wstring w(n,0);MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),w.data(),n);return w;}
static std::string WU8(const std::wstring&w){if(w.empty())return"";int n=WideCharToMultiByte(CP_UTF8,0,w.data(),(int)w.size(),0,0,0,0);std::string s(n,0);WideCharToMultiByte(CP_UTF8,0,w.data(),(int)w.size(),s.data(),n,0,0);return s;}
static std::wstring BytesW(const std::string&b){if(b.size()>=2&&(unsigned char)b[0]==0xFF&&(unsigned char)b[1]==0xFE){std::wstring w;for(size_t i=2;i+1<b.size();i+=2)w.push_back((wchar_t)((unsigned char)b[i]|((unsigned char)b[i+1]<<8)));return w;}if(b.size()>=3&&(unsigned char)b[0]==0xEF&&(unsigned char)b[1]==0xBB&&(unsigned char)b[2]==0xBF)return U8W(b.substr(3));return U8W(b);}
static std::wstring ExeDir(){wchar_t p[MAX_PATH];GetModuleFileNameW(0,p,MAX_PATH);std::wstring s=p;auto i=s.find_last_of(L"\\/");return i==std::wstring::npos?L".":s.substr(0,i);} static std::string ReadB(const std::wstring&p){std::ifstream f(p,std::ios::binary);if(!f)return{};std::ostringstream ss;ss<<f.rdbuf();return ss.str();} static void WriteB(const std::wstring&p,const std::string&d){std::ofstream f(p,std::ios::binary|std::ios::trunc);f.write(d.data(),(std::streamsize)d.size());}
static std::wstring Text(HWND h){int n=GetWindowTextLengthW(h);std::wstring s(n,0);GetWindowTextW(h,s.data(),n+1);return s;} static void SetT(HWND h,const std::wstring&s){SetWindowTextW(h,s.c_str());}
static std::wstring Trim(std::wstring s){auto f=[](wchar_t c){return c==L' '||c==L'\t'||c==L'\r'||c==L'\n';};while(!s.empty()&&f(s.front()))s.erase(s.begin());while(!s.empty()&&f(s.back()))s.pop_back();return s;} static std::wstring Lower(std::wstring s){std::transform(s.begin(),s.end(),s.begin(),[](wchar_t c){return(wchar_t)towlower(c);});return s;} static std::wstring Norm(std::wstring s){s=Lower(Trim(s));if(!s.empty()&&s.front()==L'{')s.erase(s.begin());if(!s.empty()&&s.back()==L'}')s.pop_back();return s;} static bool Uuid(const std::wstring&s){auto n=Norm(s);return n.size()>=32&&n.find(L'-')!=std::wstring::npos;}
static void Font(HWND h,HFONT f=0){SendMessageW(h,WM_SETFONT,(WPARAM)(f?f:font),TRUE);} static HWND C(const wchar_t*cls,const wchar_t*t,DWORD st,int x,int y,int w,int h,HWND p,int id,DWORD ex=0){HWND r=CreateWindowExW(ex,cls,t,st,x,y,w,h,p,(HMENU)(INT_PTR)id,gi,0);Font(r);return r;} static HWND Label(const wchar_t*t,int x,int y,int w,int h,HFONT f=0){HWND r=C(L"STATIC",t,WS_CHILD|WS_VISIBLE,x,y,w,h,wh,0);Font(r,f);return r;} static HWND Btn(const wchar_t*t,int x,int y,int w,int h,int id){return C(L"BUTTON",t,WS_CHILD|WS_VISIBLE|BS_PUSHBUTTON,x,y,w,h,wh,id);} 

static std::wstring JE(const std::wstring&s){std::wstring o;for(wchar_t c:s){if(c==L'\\')o+=L"\\\\";else if(c==L'\"')o+=L"\\\"";else if(c==L'\n')o+=L"\\n";else if(c==L'\r')o+=L"\\r";else if(c==L'\t')o+=L"\\t";else o+=c;}return o;} static std::wstring JU(const std::wstring&s){std::wstring o;for(size_t i=0;i<s.size();++i){if(s[i]==L'\\'&&i+1<s.size()){wchar_t n=s[++i];if(n==L'n')o+=L'\n';else if(n==L'r')o+=L'\r';else if(n==L't')o+=L'\t';else if(n==L'u'&&i+4<s.size()){unsigned v=0;bool ok=1;for(int k=0;k<4;k++){wchar_t h=s[i+1+k];v<<=4;if(h>=L'0'&&h<=L'9')v+=h-L'0';else if(h>=L'a'&&h<=L'f')v+=10+h-L'a';else if(h>=L'A'&&h<=L'F')v+=10+h-L'A';else ok=0;}if(ok){o+=(wchar_t)v;i+=4;}}else o+=n;}else o+=s[i];}return o;}
static bool JS(const std::wstring&o,const std::vector<std::wstring>&keys,std::wstring&out){for(auto&k:keys){auto p=o.find(L"\""+k+L"\"");if(p==std::wstring::npos)continue;p=o.find(L':',p);if(p==std::wstring::npos)continue;p=o.find(L'\"',p+1);if(p==std::wstring::npos)continue;++p;std::wstring v;bool esc=0;for(;p<o.size();++p){wchar_t c=o[p];if(esc){v+=L'\\';v+=c;esc=0;continue;}if(c==L'\\'){esc=1;continue;}if(c==L'\"')break;v+=c;}out=JU(v);return 1;}return 0;} static bool JFalse(const std::wstring&o,const std::wstring&k){auto p=o.find(L"\""+k+L"\"");if(p==std::wstring::npos)return 0;p=o.find(L':',p);if(p==std::wstring::npos)return 0;return Lower(o.substr(p+1,12)).find(L"false")!=std::wstring::npos;}
static std::vector<std::wstring> Objs(const std::wstring&j){std::vector<std::wstring> out;int d=0;bool in=0,esc=0;size_t st=0;for(size_t i=0;i<j.size();++i){wchar_t c=j[i];if(in){if(esc)esc=0;else if(c==L'\\')esc=1;else if(c==L'\"')in=0;continue;}if(c==L'\"'){in=1;continue;}if(c==L'{'){if(d++==0)st=i;}else if(c==L'}'){if(d>0&&--d==0)out.push_back(j.substr(st,i-st+1));}}return out;} static std::wstring Arr(const std::wstring&j,const std::wstring&n){auto p=j.find(L"\""+n+L"\"");if(p==std::wstring::npos)return L"";p=j.find(L'[',p);if(p==std::wstring::npos)return L"";size_t st=p+1;int d=1;bool in=0,esc=0;for(size_t i=p+1;i<j.size();++i){wchar_t c=j[i];if(in){if(esc)esc=0;else if(c==L'\\')esc=1;else if(c==L'\"')in=0;continue;}if(c==L'\"'){in=1;continue;}if(c==L'[')d++;else if(c==L']'){if(--d==0)return j.substr(st,i-st);}}return L"";}
static std::vector<std::wstring> CsvCells(const std::wstring&line){std::vector<std::wstring> c;std::wstring cur;bool q=0;for(size_t i=0;i<line.size();++i){wchar_t ch=line[i];if(ch==L'\"'){if(q&&i+1<line.size()&&line[i+1]==L'\"'){cur+=L'\"';++i;}else q=!q;}else if(ch==L','&&!q){c.push_back(cur);cur.clear();}else cur+=ch;}c.push_back(cur);return c;} static void LoadCsv(const std::wstring&t,std::vector<Snippet>&out){std::wistringstream ss(t);std::wstring line;int key=-1,val=-1,grp=-1;bool first=1;while(std::getline(ss,line)){if(!line.empty()&&line.back()==L'\r')line.pop_back();if(Trim(line).empty())continue;auto c=CsvCells(line);if(first){first=0;for(size_t i=0;i<c.size();++i){auto h=Lower(Trim(c[i]));if(h==L"keyword"||h==L"shortcut"||h==L"abbreviation")key=(int)i;if(h==L"snippet"||h==L"text"||h==L"replacement"||h==L"content")val=(int)i;if(h==L"group"||h==L"topic")grp=(int)i;}if(key>=0&&val>=0)continue;key=-1;val=-1;}if(key<0||val<0){if(c.size()>=3){grp=0;key=1;val=2;}else if(c.size()>=2){key=0;val=1;grp=-1;}else continue;}if((int)c.size()>key&&(int)c.size()>val){Snippet s{Trim(c[key]),grp>=0&&(int)c.size()>grp?Trim(c[grp]):L"CSV",c[val],true};if(!s.keyword.empty()&&!s.text.empty())out.push_back(s);}}}
static void LoadFromText(const std::wstring&t){std::vector<Snippet> r;auto go=Objs(Arr(t,L"groups"));auto co=Objs(Arr(t,L"combos"));if(co.empty())co=Objs(t);std::map<std::wstring,std::wstring> groups;for(auto&o:go){std::wstring id,n;JS(o,{L"uuid",L"id"},id);JS(o,{L"name",L"title"},n);if(!id.empty()&&!n.empty())groups[Norm(id)]=n;}for(auto&o:co){Snippet s;JS(o,{L"keyword",L"key",L"trigger",L"shortcut",L"abbreviation"},s.keyword);JS(o,{L"text",L"snippet",L"replacement",L"value",L"content",L"phrase"},s.text);JS(o,{L"group",L"groupName",L"sheetName",L"group_uuid",L"groupUuid",L"groupId"},s.group);auto ng=Norm(s.group);if(!ng.empty()&&groups.count(ng))s.group=groups[ng];else if(Uuid(s.group))s.group=L"Imported";s.keyword=Trim(s.keyword);s.enabled=!JFalse(o,L"enabled");if(!s.keyword.empty()&&!s.text.empty())r.push_back(s);}if(r.empty())LoadCsv(t,r);if(!r.empty()){std::vector<Snippet> clean;for(auto&s:r){bool dup=0;for(auto&x:clean)if(x.keyword==s.keyword&&x.text==s.text){dup=1;break;}if(!dup)clean.push_back(s);}snips=clean;}}
static void SaveSnippets(){std::wstring j=L"[\n";for(size_t i=0;i<snips.size();++i){auto&s=snips[i];j+=L"  {\n    \"keyword\": \""+JE(s.keyword)+L"\",\n    \"group\": \""+JE(s.group)+L"\",\n    \"text\": \""+JE(s.text)+L"\",\n    \"enabled\": true\n  }";if(i+1<snips.size())j+=L",";j+=L"\n";}j+=L"]\n";WriteB(dataPath,WU8(j));}
static void LoadSnippets(){snips.clear();auto b=ReadB(dataPath);if(!b.empty())LoadFromText(BytesW(b));if(snips.empty()){snips.push_back({L";hi",L"Default",L"أهلاً بحضرتك، معاك إسلام من خدمة عملاء WE. ازاي أقدر أساعد حضرتك؟",true});snips.push_back({L";thanks",L"Default",L"تحت أمرك يا فندم، سعدت بمساعدة حضرتك ونتمنالك يوم سعيد.",true});SaveSnippets();}}
static void Status(const std::wstring&s){if(statusBar)SetT(statusBar,s);} static std::wstring Prev(std::wstring t){std::replace(t.begin(),t.end(),L'\n',L' ');std::replace(t.begin(),t.end(),L'\r',L' ');if(t.size()>160)t=t.substr(0,160)+L"...";return t;}
static void Refresh(){ListView_DeleteAllItems(lv);std::wstring q=Lower(Trim(Text(searchBox)));int c=0;for(size_t i=0;i<snips.size();++i){auto&s=snips[i];auto all=Lower(s.keyword+L" "+s.group+L" "+s.text);if(q.empty()||all.find(q)!=std::wstring::npos){LVITEMW it{};it.mask=LVIF_TEXT|LVIF_PARAM;it.iItem=c;it.pszText=(LPWSTR)s.keyword.c_str();it.lParam=(LPARAM)i;int row=ListView_InsertItem(lv,&it);ListView_SetItemText(lv,row,1,(LPWSTR)(s.group.empty()?L"General":s.group.c_str()));auto p=Prev(s.text);ListView_SetItemText(lv,row,2,(LPWSTR)p.c_str());++c;}}SetT(countLbl,L"Showing "+std::to_wstring(c)+L" of "+std::to_wstring(snips.size())+L" snippets");}
static int Sel(){int s=ListView_GetNextItem(lv,-1,LVNI_SELECTED);if(s<0)return-1;LVITEMW it{};it.mask=LVIF_PARAM;it.iItem=s;return ListView_GetItem(lv,&it)?(int)it.lParam:-1;} static void LoadSel(){int i=Sel();if(i<0||i>=(int)snips.size())return;editIndex=i;SetT(kw,snips[i].keyword);SetT(gr,snips[i].group);SetT(tx,snips[i].text);Status(L"Editing "+snips[i].keyword);} static void Clear(){editIndex=-1;SetT(kw,L"");SetT(gr,L"");SetT(tx,L"");SetFocus(kw);} static int Match(const std::wstring&k){for(size_t i=0;i<snips.size();++i)if(snips[i].enabled&&snips[i].keyword==k)return(int)i;return-1;} static bool Own(){HWND fg=GetForegroundWindow();return fg==wh||IsChild(wh,fg);} 
static std::wstring KeyText(KBDLLHOOKSTRUCT*k){BYTE ks[256];if(!GetKeyboardState(ks))return L"";ks[k->vkCode]|=0x80;wchar_t buf[8]{};int r=ToUnicodeEx(k->vkCode,k->scanCode,ks,buf,7,0,GetKeyboardLayout(0));if(r>0)return std::wstring(buf,r);if(k->vkCode>='0'&&k->vkCode<='9')return std::wstring(1,(wchar_t)k->vkCode);if(k->vkCode>=VK_NUMPAD0&&k->vkCode<=VK_NUMPAD9)return std::wstring(1,(wchar_t)(L'0'+(k->vkCode-VK_NUMPAD0)));return L"";}
static void SendK(WORD vk,bool up){INPUT in{};in.type=INPUT_KEYBOARD;in.ki.wVk=vk;in.ki.dwFlags=up?KEYEVENTF_KEYUP:0;SendInput(1,&in,sizeof(INPUT));} static void Backs(int n){for(int i=0;i<n;i++){SendK(VK_BACK,0);SendK(VK_BACK,1);}} static void CtrlV(){SendK(VK_CONTROL,0);SendK('V',0);SendK('V',1);SendK(VK_CONTROL,1);} static bool ClipGet(std::wstring&out){if(!OpenClipboard(wh))return 0;HANDLE h=GetClipboardData(CF_UNICODETEXT);if(!h){CloseClipboard();return 0;}wchar_t*p=(wchar_t*)GlobalLock(h);if(!p){CloseClipboard();return 0;}out=p;GlobalUnlock(h);CloseClipboard();return 1;} static bool ClipSet(const std::wstring&s){if(!OpenClipboard(wh))return 0;EmptyClipboard();size_t bytes=(s.size()+1)*sizeof(wchar_t);HGLOBAL h=GlobalAlloc(GMEM_MOVEABLE,bytes);if(!h){CloseClipboard();return 0;}memcpy(GlobalLock(h),s.c_str(),bytes);GlobalUnlock(h);SetClipboardData(CF_UNICODETEXT,h);CloseClipboard();return 1;}
static void Expand(){if(pendingTarget){SetForegroundWindow(pendingTarget);Sleep(35);}Backs(pendingDelete);Sleep(25);hasClip=ClipGet(clipBackup);ClipSet(pendingText);Sleep(30);CtrlV();if(hasClip)SetTimer(wh,TIMER_CLIP,900,0);Status(L"Expanded snippet.");} static void Queue(int m,int del){pendingTarget=GetForegroundWindow();pendingDelete=del;pendingText=snips[m].text;buffer.clear();PostMessageW(wh,WM_EXPAND,0,0);} static bool TriggerKey(DWORD vk){return vk==VK_SPACE||vk==VK_RETURN||vk==VK_TAB;} static bool ResetKey(DWORD vk){return vk==VK_ESCAPE||vk==VK_LEFT||vk==VK_RIGHT||vk==VK_UP||vk==VK_DOWN||vk==VK_HOME||vk==VK_END||vk==VK_DELETE||vk==VK_PRIOR||vk==VK_NEXT;}
static LRESULT CALLBACK Hook(int code,WPARAM wp,LPARAM lp){if(code<0||!enabled||internalPaste)return CallNextHookEx(hook,code,wp,lp);if(wp!=WM_KEYDOWN&&wp!=WM_SYSKEYDOWN)return CallNextHookEx(hook,code,wp,lp);auto*k=(KBDLLHOOKSTRUCT*)lp;if((k->flags&LLKHF_INJECTED)||Own())return CallNextHookEx(hook,code,wp,lp);bool ctrl=(GetAsyncKeyState(VK_CONTROL)&0x8000)!=0,alt=(GetAsyncKeyState(VK_MENU)&0x8000)!=0; if(modeValue==MODE_CTRL_SPACE&&ctrl&&k->vkCode==VK_SPACE){int m=Match(buffer);if(m>=0){Queue(m,(int)buffer.size());return 1;}}
 if(k->vkCode==VK_BACK){if(!buffer.empty())buffer.pop_back();return CallNextHookEx(hook,code,wp,lp);} if(ResetKey(k->vkCode)){buffer.clear();return CallNextHookEx(hook,code,wp,lp);} if(modeValue==MODE_AUTO&&TriggerKey(k->vkCode)){int m=Match(buffer);if(m>=0){Queue(m,(int)buffer.size());return 1;}buffer.clear();return CallNextHookEx(hook,code,wp,lp);} if(ctrl||alt)return CallNextHookEx(hook,code,wp,lp); std::wstring t=KeyText(k); if(!t.empty()&&t[0]>=32){buffer+=t;if(buffer.size()>180)buffer.erase(0,buffer.size()-180); if(modeValue==MODE_CUSTOM_TEXT&&!customTrigger.empty()&&buffer.size()>customTrigger.size()&&buffer.substr(buffer.size()-customTrigger.size())==customTrigger){std::wstring key=buffer.substr(0,buffer.size()-customTrigger.size());int m=Match(key);if(m>=0){Queue(m,(int)buffer.size());return CallNextHookEx(hook,code,wp,lp);}}} return CallNextHookEx(hook,code,wp,lp);} static void StartHook(){if(!hook)hook=SetWindowsHookExW(WH_KEYBOARD_LL,Hook,GetModuleHandleW(0),0);enabled=hook!=0;Status(enabled?L"Enabled. Hook active.":L"Hook failed. Try Run as administrator.");} static void StopHook(){enabled=0;buffer.clear();Status(L"Disabled.");}
static void AddTray(){ZeroMemory(&nid,sizeof(nid));nid.cbSize=sizeof(nid);nid.hWnd=wh;nid.uID=TRAY_UID;nid.uFlags=NIF_MESSAGE|NIF_ICON|NIF_TIP;nid.uCallbackMessage=WM_TRAY;nid.hIcon=LoadIcon(0,IDI_APPLICATION);wcscpy_s(nid.szTip,L"cmd Text Expander");Shell_NotifyIconW(NIM_ADD,&nid);} static void DelTray(){if(nid.cbSize)Shell_NotifyIconW(NIM_DELETE,&nid);} static void ShowMain(){ShowWindow(wh,SW_SHOW);ShowWindow(wh,SW_RESTORE);SetForegroundWindow(wh);} static void TrayMenu(){POINT pt;GetCursorPos(&pt);HMENU m=CreatePopupMenu();AppendMenuW(m,MF_STRING,ID_TRAY_SHOW,L"Show");AppendMenuW(m,MF_STRING,ID_TRAY_ENABLE,L"Enable");AppendMenuW(m,MF_STRING,ID_TRAY_DISABLE,L"Disable");AppendMenuW(m,MF_SEPARATOR,0,0);AppendMenuW(m,MF_STRING,ID_TRAY_EXIT,L"Exit");SetForegroundWindow(wh);TrackPopupMenu(m,TPM_RIGHTBUTTON,pt.x,pt.y,0,wh,0);DestroyMenu(m);}
static void UpdateMode(){modeValue=(int)SendMessageW(modeBox,CB_GETCURSEL,0,0);if(modeValue<0)modeValue=MODE_AUTO;BOOL show=modeValue==MODE_CUSTOM_TEXT;ShowWindow(customBox,show?SW_SHOW:SW_HIDE);ShowWindow(setCustomBtn,show?SW_SHOW:SW_HIDE);if(modeValue==MODE_AUTO)SetT(modeStatus,L"Mode: Automatic — keyword then Space / Enter / Tab");else if(modeValue==MODE_CTRL_SPACE)SetT(modeStatus,L"Mode: Ctrl + Space");else SetT(modeStatus,L"Custom trigger: "+customTrigger);} static void SetCustom(){auto v=Text(customBox);if(Trim(v).empty()){MessageBoxW(wh,L"اكتب رمز أو حرف أو كلمة للتفعيل. مثال: ؛ أو ب أو ##",L"cmd Text Expander",MB_ICONWARNING);return;}customTrigger=v;SetT(customBox,customTrigger);UpdateMode();Status(L"Custom trigger set: "+customTrigger);} 
static void SaveCur(){std::wstring k=Trim(Text(kw)),g=Trim(Text(gr)),t=Text(tx);if(k.empty()){MessageBoxW(wh,L"Keyword is required.",L"cmd Text Expander",MB_ICONWARNING);SetFocus(kw);return;}if(t.empty()){MessageBoxW(wh,L"Snippet text is required.",L"cmd Text Expander",MB_ICONWARNING);SetFocus(tx);return;}Snippet s{k,g,t,true};if(editIndex>=0&&editIndex<(int)snips.size())snips[editIndex]=s;else snips.push_back(s);SaveSnippets();Refresh();Clear();Status(L"Saved.");}
static std::wstring Pick(bool save){wchar_t file[MAX_PATH]=L"";OPENFILENAMEW ofn{};ofn.lStructSize=sizeof(ofn);ofn.hwndOwner=wh;ofn.lpstrFile=file;ofn.nMaxFile=MAX_PATH;ofn.lpstrFilter=L"Backup/CSV files (*.json;*.btbackup;*.csv)\0*.json;*.btbackup;*.csv\0All files (*.*)\0*.*\0";ofn.Flags=OFN_EXPLORER|OFN_PATHMUSTEXIST|(save?OFN_OVERWRITEPROMPT:OFN_FILEMUSTEXIST);if(save)wcscpy_s(file,L"cmd-snippets.json");return(save?GetSaveFileNameW(&ofn):GetOpenFileNameW(&ofn))?file:L"";} static void Import(){auto p=Pick(0);if(p.empty())return;auto b=ReadB(p);if(b.empty()){MessageBoxW(wh,L"Could not read file.",L"cmd Text Expander",MB_ICONERROR);return;}auto old=snips;snips.clear();LoadFromText(BytesW(b));if(snips.empty()){snips=old;MessageBoxW(wh,L"No valid snippets found. Try Beeftext .btbackup, JSON, or CSV.",L"cmd Text Expander",MB_ICONERROR);return;}SaveSnippets();Refresh();Clear();Status(L"Imported "+std::to_wstring(snips.size())+L" snippets.");} static void Export(){auto p=Pick(1);if(p.empty())return;SaveSnippets();WriteB(p,ReadB(dataPath));Status(L"Backup exported.");}
static void BuildList(){lv=CreateWindowExW(WS_EX_CLIENTEDGE,WC_LISTVIEWW,L"",WS_CHILD|WS_VISIBLE|LVS_REPORT|LVS_SINGLESEL|LVS_SHOWSELALWAYS,18,372,1060,320,wh,(HMENU)ID_LIST,gi,0);Font(lv);ListView_SetExtendedListViewStyle(lv,LVS_EX_FULLROWSELECT|LVS_EX_GRIDLINES|LVS_EX_DOUBLEBUFFER);LVCOLUMNW c{};c.mask=LVCF_TEXT|LVCF_WIDTH;c.pszText=(LPWSTR)L"Keyword";c.cx=150;ListView_InsertColumn(lv,0,&c);c.pszText=(LPWSTR)L"Group";c.cx=160;ListView_InsertColumn(lv,1,&c);c.pszText=(LPWSTR)L"Preview";c.cx=720;ListView_InsertColumn(lv,2,&c);} static void Layout(){RECT r;GetClientRect(wh,&r);int W=r.right,H=r.bottom;MoveWindow(statusBar,18,H-30,W-36,24,TRUE);MoveWindow(searchBox,18,332,420,30,TRUE);MoveWindow(countLbl,W-340,336,320,24,TRUE);MoveWindow(lv,18,372,W-36,H-410,TRUE);ListView_SetColumnWidth(lv,0,150);ListView_SetColumnWidth(lv,1,160);ListView_SetColumnWidth(lv,2,W-370);} 
static void BuildUI(){Label(L"cmd Text Expander",18,14,360,34,titleFont);Label(L"Expansion Mode",650,18,150,24,boldFont);modeBox=C(WC_COMBOBOXW,L"",WS_CHILD|WS_VISIBLE|CBS_DROPDOWNLIST,650,46,205,160,wh,ID_MODE);SendMessageW(modeBox,CB_ADDSTRING,0,(LPARAM)L"Automatic");SendMessageW(modeBox,CB_ADDSTRING,0,(LPARAM)L"Ctrl + Space");SendMessageW(modeBox,CB_ADDSTRING,0,(LPARAM)L"Custom trigger");SendMessageW(modeBox,CB_SETCURSEL,0,0);customBox=C(L"EDIT",customTrigger.c_str(),WS_CHILD|WS_BORDER|ES_AUTOHSCROLL,865,46,90,28,wh,ID_CUSTOM,WS_EX_CLIENTEDGE);setCustomBtn=Btn(L"Set",965,46,58,28,ID_SET_CUSTOM);Btn(L"Enable",930,82,78,32,ID_ENABLE);Btn(L"Disable",1016,82,78,32,ID_DISABLE);modeStatus=Label(L"",18,54,610,24,boldFont);Label(L"Keyword",18,102,90,22,boldFont);kw=C(L"EDIT",L"",WS_CHILD|WS_VISIBLE|WS_BORDER|ES_AUTOHSCROLL,112,100,260,30,wh,ID_KEYWORD,WS_EX_CLIENTEDGE);Label(L"Group",392,102,70,22,boldFont);gr=C(L"EDIT",L"",WS_CHILD|WS_VISIBLE|WS_BORDER|ES_AUTOHSCROLL,470,100,260,30,wh,ID_GROUP,WS_EX_CLIENTEDGE);Label(L"Snippet Text",18,144,100,22,boldFont);tx=C(L"EDIT",L"",WS_CHILD|WS_VISIBLE|ES_MULTILINE|ES_AUTOVSCROLL|WS_VSCROLL,112,140,618,130,wh,ID_TEXT,WS_EX_CLIENTEDGE);Btn(L"Save",752,140,90,32,ID_SAVE);Btn(L"New",852,140,90,32,ID_NEW);Btn(L"Delete",952,140,90,32,ID_DELETE);Btn(L"Copy",752,180,90,32,ID_COPY);Btn(L"Import",852,180,90,32,ID_IMPORT);Btn(L"Export",952,180,90,32,ID_EXPORT);Label(L"Search",18,306,90,22,boldFont);searchBox=C(L"EDIT",L"",WS_CHILD|WS_VISIBLE|WS_BORDER|ES_AUTOHSCROLL,18,332,420,30,wh,ID_SEARCH,WS_EX_CLIENTEDGE);countLbl=Label(L"",760,336,320,24,boldFont);BuildList();statusBar=Label(L"Ready",18,710,1060,24,boldFont);UpdateMode();}
static LRESULT CALLBACK Wnd(HWND h,UINT m,WPARAM w,LPARAM l){switch(m){case WM_CREATE:wh=h;dataPath=ExeDir()+L"\\snippets.json";font=CreateFontW(17,0,0,0,FW_NORMAL,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");boldFont=CreateFontW(17,0,0,0,FW_SEMIBOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");titleFont=CreateFontW(28,0,0,0,FW_BOLD,0,0,0,DEFAULT_CHARSET,0,0,CLEARTYPE_QUALITY,0,L"Segoe UI");bgBrush=CreateSolidBrush(C_BG);fieldBrush=CreateSolidBrush(RGB(255,255,255));LoadSnippets();AddTray();BuildUI();Refresh();StartHook();return 0;case WM_ERASEBKGND:{RECT r;GetClientRect(h,&r);FillRect((HDC)w,&r,bgBrush);return 1;}case WM_CTLCOLORSTATIC:{SetBkMode((HDC)w,TRANSPARENT);SetTextColor((HDC)w,C_TEXT);return(LRESULT)bgBrush;}case WM_CTLCOLOREDIT:{SetBkColor((HDC)w,RGB(255,255,255));SetTextColor((HDC)w,RGB(15,35,45));return(LRESULT)fieldBrush;}case WM_SIZE:if(w==SIZE_MINIMIZED){ShowWindow(h,SW_HIDE);return 0;}Layout();return 0;case WM_TRAY:if(l==WM_LBUTTONDBLCLK)ShowMain();else if(l==WM_RBUTTONUP)TrayMenu();return 0;case WM_EXPAND:internalPaste=1;Expand();internalPaste=0;return 0;case WM_TIMER:if(w==TIMER_CLIP){KillTimer(h,TIMER_CLIP);if(hasClip)ClipSet(clipBackup);hasClip=0;}return 0;case WM_NOTIFY:{auto*nm=(NMHDR*)l;if(nm->idFrom==ID_LIST&&nm->code==NM_DBLCLK)LoadSel();return 0;}case WM_COMMAND:{int id=LOWORD(w);if(id==ID_SAVE)SaveCur();else if(id==ID_NEW)Clear();else if(id==ID_DELETE){int i=Sel();if(editIndex>=0)i=editIndex;if(i>=0&&i<(int)snips.size()){snips.erase(snips.begin()+i);SaveSnippets();Refresh();Clear();}}else if(id==ID_COPY)ClipSet(Text(tx));else if(id==ID_IMPORT)Import();else if(id==ID_EXPORT)Export();else if(id==ID_ENABLE||id==ID_TRAY_ENABLE)StartHook();else if(id==ID_DISABLE||id==ID_TRAY_DISABLE)StopHook();else if(id==ID_MODE&&HIWORD(w)==CBN_SELCHANGE)UpdateMode();else if(id==ID_SET_CUSTOM)SetCustom();else if(id==ID_TRAY_SHOW)ShowMain();else if(id==ID_TRAY_EXIT)DestroyWindow(h);else if(id==ID_SEARCH&&HIWORD(w)==EN_CHANGE)Refresh();return 0;}case WM_DESTROY:DelTray();if(hook)UnhookWindowsHookEx(hook);DeleteObject(font);DeleteObject(titleFont);DeleteObject(boldFont);DeleteObject(bgBrush);DeleteObject(fieldBrush);PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);} 
int APIENTRY wWinMain(HINSTANCE h,HINSTANCE,LPWSTR,int n){gi=h;INITCOMMONCONTROLSEX ic{sizeof(ic),ICC_LISTVIEW_CLASSES};InitCommonControlsEx(&ic);WNDCLASSW wc{};wc.lpfnWndProc=Wnd;wc.hInstance=h;wc.hCursor=LoadCursor(0,IDC_ARROW);wc.hIcon=LoadIcon(0,IDI_APPLICATION);wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);wc.lpszClassName=L"CmdTextExpanderFinal2";RegisterClassW(&wc);HWND wnd=CreateWindowExW(0,wc.lpszClassName,L"cmd Text Expander",WS_OVERLAPPEDWINDOW,100,80,1120,760,0,0,h,0);ShowWindow(wnd,n);UpdateWindow(wnd);MSG msg;while(GetMessageW(&msg,0,0,0)){TranslateMessage(&msg);DispatchMessageW(&msg);}return 0;}
